name: CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-deploy:
    name: Build and Deploy API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -f TP4SCS.Solution/Dockerfile -t hieu15402/tp4scsapi:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push the Docker image to Docker Hub
        run: docker push hieu15402/tp4scsapi:latest
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            if [ "$(docker ps -aq -f name=tp4scsapi)" ]; then
                echo "Stopping tp4scsapi..."
                docker stop tp4scsapi || true
                sleep 5  # Cho thời gian để container dừng hoàn toàn
                
                if [ "$(docker ps -aq -f name=tp4scsapi)" ]; then
                    echo "Removing tp4scsapi..."
                    docker rm tp4scsapi || { echo "Failed to remove tp4scsapi"; exit 1; }
                else
                    echo "Container tp4scsapi was already removed or doesn't exist."
                fi
            else
                echo "tp4scsapi does not exist."
            fi

            # Xóa các image không có tag
            docker images --filter=reference='hieu15402/tp4scsapi' --format '{{.ID}} {{.Tag}}' | grep '<none>' | awk '{print $1}' | xargs -I {} docker rmi -f {}
            
            # Kéo image mới nhất từ Docker Hub
            docker pull hieu15402/tp4scsapi

            # Kiểm tra xem cổng 8080 có sẵn không trước khi chạy container
            if lsof -i :8080; then
                echo "Port 8080 is in use, container might not start."
                exit 1
            fi

            # Chạy container mới
            docker run -d -p 8080:8080 --name tp4scsapi --restart always hieu15402/tp4scsapi || { echo "Failed to start tp4scsapi container"; exit 1; }

